### ISSUE TITLE
Key errors

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/script.module.infotagger#4]
I'm getting JSON directly from Kodi library using JSON-RPC and feeding it directly into the infotagger module but I'm getting a bunch of key errors:-

```
2023-03-25 17:01:28.745 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: art
2023-03-25 17:01:28.745 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: file
2023-03-25 17:01:28.746 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: label
2023-03-25 17:01:28.746 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: movieid
2023-03-25 17:01:28.746 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: ratings
2023-03-25 17:01:28.746 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: resume
2023-03-25 17:01:28.746 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: runtime
2023-03-25 17:01:28.746 T:16860    info <general>: [script.module.infotagger] set_info:
                                                   KeyError: streamdetails
```

This is the JSON I'm using:- https://pastebin.com/RS8Jmy9c

This is the simple test code I'm using:-
```
def test():
        id = int(sys.argv[1])
        li = []
        finalList = []

        # Get movies
        json_query = json_call('VideoLibrary.GetMovies',
                               properties=JSON_MAP['movie_properties'],
                               sort=self.sort_lastplayed,
                               query_filter={'and': [self.filter_inprogress]}
                               )
        try:
            json_query = json_query['result']['movies']
        except Exception:
            pass
        else:
            for movie in json_query:
                li.append(movie)

        for item in li:
            guiItem = xbmcgui.ListItem(label=item['title'], path=item['file'], offscreen=True)
            guiItem.setIsFolder(False)
            guiItem.setArt(item['art'])

            info_tag = ListItemInfoTag(guiItem, 'video')
            info_tag.set_info(item)
            info_tag.set_cast(item['cast'])
            info_tag.set_stream_details(item['streamdetails'])
            finalList.append(guiItem)

        xbmcplugin.addDirectoryItems(id, [(li.getPath(), li, li.isFolder()) for li in finalList if li])
        xbmcplugin.endOfDirectory(handle=id)
        xbmcplugin.setPluginCategory(id, 'test')
        xbmcplugin.setContent(id, 'mixed')
```

**Comment by jurialmunkey** [comment]
You're getting keyerrors because those are not valid infolabels. You should only be passing the infolabel dictionary to set_info(). It is a replacement for listitem.setInfo()

**Comment by jurialmunkey** [comment]
FYI - What jsonrpc returns is not a 1:1 match for infolabels. It has always required wrangling to a new dictionary to pass back to ListItem.setInfo() -- If you were simply passing this dictionary back to setInfo() before, then your code was incorrect and you were likely missing a lot of metadata. The only difference is now error messages are verbose to highlight where you've gone wrong.

You can see which infolabels Kodi ListItem.setInfo() accepts in the docs: 
https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#ga0f1e91e1d5aa61d8dd0eac90e8edbf18

**"art"** 
Set via [ListItem.setArt](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#ga92f9aeb062ff50badcb8792d14a37394) 
Should be popped from the infolabels dictionary

**"file"** 
Set in the [ListItem(path=item['path'])](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#gaa45d3bbf41b166e9eeb02cf6bb55919c)
Should be popped and remapped to "path" in the infolabels.

**"label"** 
Set directly to the [ListItem(label=item['label'])](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#gaa45d3bbf41b166e9eeb02cf6bb55919c). 
Should be popped from the infolabel dictionary.

**"movieid"** 
Should be popped and remapped to "dbid" in infolabels for [setInfo](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#ga0f1e91e1d5aa61d8dd0eac90e8edbf18)

**"ratings"** 
In Matrix, set individually using [ListItem.setRating()](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#ga0451d6e40ac2007eced53bcec09d8fd5). 
In Nexus, set via info tag [setRatings()](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python___info_tag_video.html#ga2edf85d7db24344be53437d29dfc99b7) as whole dictionary or can use setRating() for individual ratings.

You can access the InfoTagVideo from ListItemInfoTag using `._info_tag` internal attribute 
i.e.`info_tag._info_tag.setRatings(ratings)`

Should be popped from infolabels.

**"resume"**
In Matrix, set via [special infoproperties ResumeTime](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python__xbmcgui__listitem.html#ga96f1976952584c91e6d59c310ce86a25). 
In Nexus, set via info tag [setResumePoint()](https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit/group__python___info_tag_video.html#ga743cde8f2dd896f9356ab43ab70d710a) i.e. `info_tag._info_tag.setResumePoint()` 
Should be popped from infolabels.

There is also a method in infotagger for backward compatibility with the special properties infoproperties dictionary but there's no point using that if you weren't adding these to infoproperties in the first place (you were simply missing this info before).

**"runtime"** 
In Matrix, set via "TotalTime" special property in conjunction with resume as above.
In Nexus, set via setResumePoint setter in conjunction with resume as above.
Should be popped from infolabels.

**"streamdetails"** 
Set using the set_stream_details method in infotagger.
Should be popped from infolabels.


[Edited for formatting]

**Comment by roidy** [comment]
Thanks for the clear explanation, I incorrectly assumed you could just use a JSON-RPC response directly and the module would take care of everything.

**Comment by roidy** [comment]
Sorry to bother you again, but the only one I can't figure out is ratings. I pop my ratings from the JSON-RPC response which gives the following:-

```
{
    "imdb": {
        "default": false,
        "rating": 5.400000095367432,
        "votes": 576
     },
     "themoviedb": {
        "default": true,
        "rating": 6.699999809265137,
        "votes": 7
     },
     "trakt": {
        "default": false,
        "rating": 6.186669826507568,
        "votes": 75
     }
}
```

However when I try to use `info_tag._info_tag.setRatings(ratings)` I get the following error.

2023-03-26 08:13:00.198 T:31803   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: The parameter "value" must be either a Tuple or a List.
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.tiny.helper/plugin.py", line 347, in <module>
                                                       Main()
                                                     File "/storage/.kodi/addons/script.tiny.helper/plugin.py", line 58, in __init__
                                                       self.test()
                                                     File "/storage/.kodi/addons/script.tiny.helper/plugin.py", line 138, in test
                                                       info_tag._info_tag.setRatings(ratings)
                                                   TypeError: The parameter "value" must be either a Tuple or a List.
                                                   -->End of Python script error report<--
